### PR TITLE
DB Query Script

### PR DESCRIPTION
**Pull request by Humoud**
Created a script (query.py) which allows the user to query the Elastic DB with ease and it also allows further static analysis to be conducted on the samples colllected.
The static analysis features currently implemented in this script are basic and focus on Windows PE files and they are:
1. Calculate ImpHash
2. Show DLL imports

I tried to follow the structure of the inhale.py script as well as its output formatting and colors, to make the project consistent and because it's beatiful.
Note that an extra dependency has been added to the requirements.txt file which is pefile, this library is used to calculate ImpHash and to show the imported DLLs.
I also updated the README.md to show how the script can be used (there might be typos it's really late here).
Thanks for the project and I hope I can help make it grow.

Below are screenshots of the script in action:

### Queries 
Notice how you can select which fields you want to see from the returned DB query:

image

image

image

### Queries + Some Operations
Calculate ImpHash:

image

Display DLL imports:

image

### CODE REVIEW

**Comment by ProductiveAsparagus56** [comment]
A shame that this hasn't been merged yet, will definitely check out your repo cause this feature seems awesome.

**Comment by Humoud** [comment]
@Audition-CSBlock Thanks, I just made another pull request. I dockerized the project, I hope @netspooky approves it. I liked your pull request but sadly I am not sure if it can be merged with the new pull request I made since I moved all project files except README.md and requirements.txt to a folder I created called "app". Any thoughts on this?

I create the app folder and moved files to it to make sure that less docker image layers are created. In other words, I wanted to reduce the "COPY" instructions in the Dockerfile as this will reduce the image size. Currently, only the requirements.txt file is copied to the container. The app folder is mounted in to the container.

And finally I added a missing dependency "requests" to the requirements.txt file.
I did not modify any code.

**Comment by ProductiveAsparagus56** [comment]
@Humoud Woops, sorry for the insanely long response time but yes i can change my pull request accordingly 👍 .
Although i had a different idea; Should i fork the project fully and continue it there? I think this project got left behind so i might as well fork/clone it? Ideas?

**Comment by Humoud** [comment]
@Audition-CSBlock No probs and I like that idea! Fork it and we'll continue from there.

**Comment by ProductiveAsparagus56** [comment]
#5 It's done, you can make your PR there.

**Pull request closed without merging**
